pre-commit:
  parallel: true
  commands:
    "trivy-secrets.sh":
      run: .lefthook/trivy-secrets.sh
      tags:
        - security
    spotlessApply:
      run: .lefthook/spotless-apply.sh
      stage_fixed: true
