name: Dependabot Automations

on:
  pull_request_target:
    paths:
      - 'build.gradle.kts'
      - '**/build.gradle.kts'
      - 'gradle/libs.versions.toml'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - 'settings.gradle.kts'

jobs:
  update-verification:
    if: github.actor == 'dependabot[bot]'
    uses: digitalservicebund/ris-assertions-common/.github/workflows/update-verification-metadata.yml@fd512a01d8dc8a67d3415cf46626401735c5b1b3
    with:
      java-version: '25'