name: Pipeline

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - ".github/dependabot.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/dependabot.yml"
  workflow_dispatch:

jobs:
  pipeline:
    uses: digitalservicebund/ris-migration-common/.github/workflows/pipeline.yml@8a336214e6802693fd4e0e62c6c65592c0f9500e
    secrets: inherit
