name: Pipeline

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - ".github/dependabot.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/dependabot.yml"
  workflow_dispatch:

jobs:
  pipeline:
    uses: digitalservicebund/ris-migration-common/.github/workflows/pipeline.yml@e1ff9ead8c0090874ca28760b378da68da2f12cb
    secrets: inherit

  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: "25"
          distribution: "temurin"
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@3f5f9adaf7d9fecd50b5935e54106014257a94e6
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f5f9adaf7d9fecd50b5935e54106014257a94e6
      - name: Check licenses
        run: ./gradlew checkLicense
