name: Publish package to GitHub Packages

permissions:
  contents: read

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  pipeline:
    uses: digitalservicebund/ris-migration-common/.github/workflows/pipeline.yml@main
    secrets: inherit

  publish:
    needs: [pipeline]
    uses: digitalservicebund/ris-migration-common/.github/workflows/publish-package.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
